/**
 * Curated lists for phrase extraction
 */

// Prepositional phrases (multi-word prepositions)
export const PREPOSITIONAL_PHRASES = [
  "in terms of",
  "as a result of",
  "due to",
  "because of",
  "in addition to",
  "in spite of",
  "with respect to",
  "in accordance with",
  "on the other hand",
  "in order to",
  "based on",
  "according to",
  "in front of",
  "in charge of",
  "in response to",
  "at the expense of",
  "by means of",
  "for the sake of",
  "in case of",
  "in favor of",
  "in lieu of",
  "in place of",
  "in regard to",
  "in relation to",
  "in view of",
  "on account of",
  "on behalf of",
  "on top of",
  "with regard to",
  "with reference to",
  "as opposed to",
  "as well as",
  "apart from",
  "aside from",
  "except for",
  "instead of",
  "prior to",
  "subsequent to",
  "thanks to",
  "up to",
];

// Phrasal verbs (2-word and 3-word)
export const PHRASAL_VERBS = [
  // 2-word phrasal verbs
  "carry out",
  "set up",
  "look into",
  "find out",
  "point out",
  "work out",
  "figure out",
  "take over",
  "put off",
  "turn down",
  "bring up",
  "make up",
  "give up",
  "run into",
  "deal with",
  "lead to",
  "result in",
  "look for",
  "look at",
  "look after",
  "look forward",
  "pick up",
  "put up",
  "put down",
  "put on",
  "take off",
  "take on",
  "take up",
  "turn on",
  "turn off",
  "turn out",
  "get up",
  "get out",
  "get over",
  "get through",
  "go on",
  "go through",
  "go over",
  "come up",
  "come back",
  "come across",
  "break down",
  "break up",
  "break out",
  "bring about",
  "bring back",
  "call off",
  "call for",
  "check out",
  "check in",
  "cut off",
  "cut down",
  "fill in",
  "fill out",
  "give in",
  "hand in",
  "hand out",
  "hold on",
  "keep up",
  "keep on",
  "lay off",
  "leave out",
  "let down",
  "pass on",
  "pass out",
  "pay off",
  "pull out",
  "run out",
  "set off",
  "show up",
  "shut down",
  "sort out",
  "stand out",
  "stick to",
  "sum up",
  "throw away",
  "try on",
  "try out",
  "use up",
  "wake up",
  "wear out",
  "write down",
  // 3-word phrasal verbs
  "come up with",
  "look forward to",
  "put up with",
  "get rid of",
  "get along with",
  "catch up with",
  "keep up with",
  "come down with",
  "look down on",
  "look up to",
  "make up for",
  "run out of",
  "get away with",
  "go along with",
  "cut down on",
  "face up to",
  "live up to",
  "stand up for",
  "get on with",
  "go ahead with",
];

// English stopwords (150+)
export const STOPWORDS = new Set([
  "a", "an", "the", "and", "or", "but", "if", "then", "else", "when",
  "at", "by", "for", "with", "about", "against", "between", "into", "through",
  "during", "before", "after", "above", "below", "to", "from", "up", "down",
  "in", "out", "on", "off", "over", "under", "again", "further", "then", "once",
  "here", "there", "where", "why", "how", "all", "each", "few", "more", "most",
  "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so",
  "than", "too", "very", "s", "t", "can", "will", "just", "don", "should",
  "now", "i", "me", "my", "myself", "we", "our", "ours", "ourselves", "you",
  "your", "yours", "yourself", "yourselves", "he", "him", "his", "himself",
  "she", "her", "hers", "herself", "it", "its", "itself", "they", "them",
  "their", "theirs", "themselves", "what", "which", "who", "whom", "this",
  "that", "these", "those", "am", "is", "are", "was", "were", "be", "been",
  "being", "have", "has", "had", "having", "do", "does", "did", "doing",
  "would", "could", "ought", "i'm", "you're", "he's", "she's", "it's",
  "we're", "they're", "i've", "you've", "we've", "they've", "i'd", "you'd",
  "he'd", "she'd", "we'd", "they'd", "i'll", "you'll", "he'll", "she'll",
  "we'll", "they'll", "isn't", "aren't", "wasn't", "weren't", "hasn't",
  "haven't", "hadn't", "doesn't", "don't", "didn't", "won't", "wouldn't",
  "shan't", "shouldn't", "can't", "cannot", "couldn't", "mustn't", "let's",
  "that's", "who's", "what's", "here's", "there's", "when's", "where's",
  "why's", "how's", "because", "as", "until", "while", "of", "both", "either",
  "neither", "also", "still", "already", "yet", "ever", "never", "always",
  "often", "sometimes", "usually", "perhaps", "maybe", "however", "therefore",
  "thus", "hence", "although", "though", "even", "whether", "since", "unless",
]);

// Noun suffixes for heuristic detection
export const NOUN_SUFFIXES = [
  "tion", "sion", "ment", "ness", "ity", "ship", "ence", "ance",
  "er", "or", "ist", "ism", "dom", "hood", "age", "ure", "ery",
  "ing", "al", "ology", "graphy", "ics",
];

// Adjective suffixes
export const ADJECTIVE_SUFFIXES = [
  "al", "ive", "ous", "able", "ible", "ic", "ary", "ful", "less",
  "ent", "ant", "ory", "ical", "eous", "ious",
];
